### PR TITLE
Use day instead of time for caching

### PR DESCRIPTION
**Pull request by robbinjanssen**
### What does it do?
This extends the caching system with 2 new cases, making it a total of 4 cases.

Basically it:
- Updates the cache if the current value is bigger or equal to the cache value
- Use the cache value if the current value is smaller (for example when your inverter resets to early)
- If the day has passed and the current value is equal to the cached value (if your inverter did not reset yet), then output 0
- If the day has passed and the current value is no longer equal to the cached value, use the currentValue and update the cacheDay

I'll run it overnight and see if it works as expected :-)

### CODE REVIEW

**Comment by robbinjanssen** [comment]
@gerard33 do you mind reviewing this PR? 🎉

**Comment by gerard33** [comment]
Looks good to me.

Can't do any testing while my inverter all of a sudden has no connection to my wifi anymore 😮

And I have put a password on the wifi SSID from the inverter itself (out of the box it's unprotected), but I have not written that password down 🙈 . So can't connect to the inverter directly to set-up the connection to my wifi anymore.

**Comment by robbinjanssen** [comment]
Well that sucks 😂 I think you can reset the connection through the menu, depends on your inverter though.

Meanwhile I've tested my fix and it works like a charm, with caching on 👍

**Comment by gerard33** [comment]
I have reset the inverter by following steps 1-4 of the manual from this link -> https://www.sungevity.nl/files/cc/Omnik-manual-4-8-17.pdf

That brought the connection to the wifi back without any further steps needed.
And now to write down the password I set for the wifi of the inverter ;-)
And going to test the new version you made of course.

**Pull request merged**
